### ISSUE TITLE
Are you willing to accept PR for this repo

### ISSUE THREAD

**Issue by HMekaXP** [venkivijay/Java-Solutions-TCS-Xplore-Proctored-Assessment#11]

**Comment by venkivijay** [comment]
Hey @HMekaXP, 
Yes, PR's will be accepted. Please have a glance at [Contribution Guidelines](https://github.com/venkivijay/Java-Solutions-TCS-Xplore-Proctored-Assessment/blob/master/.github/CONTRIBUTING.md) before raising PR.
