### ISSUE TITLE
Player Get average of Runs 

### ISSUE THREAD

**Issue by SUBHAROOP** [venkivijay/Java-Solutions-TCS-Xplore-Proctored-Assessment#3]
can u tell me in output of this problem Player Get average of Runs why virat kohli grade is not printed

**Comment by venkivijay** [comment]
Ya sure. The player's grade will only be printed if the player's matchesPlayed is greater than the target int we provide. In the sample input, the target value is 100. All the players except Virat have matchesPlayed value greater than the target value. So except Virat all the player's grades are calculated and printed. Hope this helps!

**Comment by SUBHAROOP** [comment]
ok thanks
